language: clojure
sudo: required
addons:
  postgresql: "9.5"
lein: lein2
jdk:
  - oraclejdk8
before_script:
  - sudo -u postgres psql -p 5433 -c "CREATE USER test WITH PASSWORD 'test'"
  - sudo -u postgres psql -p 5433 -c 'ALTER ROLE test WITH SUPERUSER'
  - sudo -u postgres psql -p 5433 -c 'CREATE DATABASE test_db;'
script: env DATABASE_URL="jdbc:postgresql://localhost:5432/test_db?user=test&password=test&stringtype=unspecified" lein2 do clean, javac, test

